from . import constants
from . import partner
from . import partner_names
from . import partner_profiles
from . import partner_relations
from . import partner_street_names
from . import partner_tweak_addresses
from . import project
from . import opportunity
from . import competitor
from . import product_attribute
from . import product_attribute_related
from . import product_brand
from . import product_state
from . import report
from . import waybill
from . import product_attribute_set
from . import product_attribute_tag
from . import product_product
from . import product_template
from . import sale_order
from . import tracking
from . import product_product_code
# from . import x_product_attribute_value_supplier
